# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
 branches:
  include:
    - main
 paths:
  include:
    - 'Downgrooves.WebApi'
    - 'Downgrooves.Service'
    - 'Downgrooves.Persistence'
    - 'Downgrooves.Domain'

pool: 
  name: Default
  demands:
  - agent.name -equals NEPTUNE

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: sdk
    version: '5.0.x'
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '*'

- script: nuget restore -ApiKey 3MLnUWJV2HgHwTjEpBwvrNzypp77AzCrekC8Z5nkEVy5ykcTZqWsa5SnY2bnwGya

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    workingDirectory: $(Build.SourcesDirectory)

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: true
    projects: '**/Downgrooves.WebApi/*.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true
    workingDirectory: $(Build.SourcesDirectory)
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: '$(Build.BuildId)'

